-- Drop table

-- DROP TABLE PUBLIC."USER";

CREATE TABLE PUBLIC."USER" (
	ID BIGINT NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	AGE BIGINT,
	CONSTRAINT TEST_PK PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX PRIMARY_KEY_2 ON PUBLIC."USER" (ID);
